languageCode = "en-us"
title = "SlickSavers"
[params]
prism_syntax_highlighting = true
  [params.prism]
    languages = [
      "markup",
      "css",
      "clike",
      "javascript"
    ]
    plugins = [
      "normalize-whitespace",
      "toolbar",
      "copy-to-clipboard"
    ]
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
tags = "/tags/:year/:month/:day/:slug/" 
home = "/tags/{{ now.Format "2006-01-02" }}" 
