languageCode = "en-us"
title = "My New Netlify Victor Hugo Site"
[params]
prism_syntax_highlighting = true
  [params.prism]
    languages = [
      "markup",
      "css",
      "clike",
      "javascript"
    ]
    plugins = [
      "normalize-whitespace",
      "toolbar",
      "copy-to-clipboard"
    ]
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = false
