name: Cleanup Old Hugo Content

on:
  workflow_dispatch:  # run manually in GitHub Actions tab
  

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install datetime python-frontmatter

      - name: Run cleanup script
        run: python cleanup.py

      - name: Push changes using PAT
        env:
            GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git config --global --add safe.directory "$GITHUB_WORKSPACE"
            git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
            
            git add -A
            if git diff --cached --quiet; then
              echo "No changes to commit."
            else
              git commit -m "Automated: Remove Hugo content tagged 'amazon'"
              git push
            fi
