name: Post Hugo Content to Facebook
on:
  push:
    paths:
      - "site/content/post/**"  # Trigger when new content is added

jobs:
  post_to_facebook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Print Run ID and Name
        run: |
          echo "Run ID: ${{ github.run_id }}"
          echo "Run Name: ${{ github.run_name }}"

      - name: Get New Content Filename
        id: get_filename
        run: echo "NEW_CONTENT=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep 'site/content/post/')" >> $GITHUB_ENV

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: pip install requests python-frontmatter

      - name: Run Facebook Posting Script
        run: python post.py
        env:
          NEW_CONTENT: ${{ env.NEW_CONTENT }}

