name: Post Hugo Content to Facebook
on:
  push:
    paths:
      - "site/content/post/**"  # Trigger when new content is added

jobs:
  post_to_facebook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Print Run ID and Name
        run: |
          echo "Run ID: ${{ github.run_id }}"
          echo "Run Name: ${{ github.run_name }}"

      - name: Get changed files
        id: changes
        run: |
          echo "Getting changes from ${{ github.event.before }} to ${{ github.sha }}"
          CHANGED=$(git diff --name-only --diff-filter=AM ${{ github.event.before }} ${{ github.sha }})
          echo "NEW_CONTENT=$CHANGED" >> $GITHUB_ENV

      - name: Use the files
        run: echo "Files changed:$NEW_CONTENT"

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: pip install requests python-frontmatter python-slugify

      - name: Run Facebook Posting Script
        run: python post.py
        env:
          NEW_CONTENT: ${{ env.NEW_CONTENT }}

